version: '3.6'
services:
  frontend:
    image: "intelli-train:frontend"
    # nvidia-docker:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # default runtime: nvidia
    # runtime: nvidia
    # workspace:
    volumes:
      - $PWD/workspace:/workspace
    # webcam:
    devices:
      - /dev/video0:/dev/video0
    # vnc:
    ports:
      - 5901:5901

